### ISSUE TITLE
Initialized the model to use GPT 4 but GPT 3 is used ?

### ISSUE THREAD

**Issue by dcssi** [zhudotexe/kani#15]
I initialized my model like this
OpenAIEngine(api_key, model="gpt-4")

However if I ask the model what version it is,  it replies its gpt 3  ( yes i named my chatbot trevor"

[' Trevor, are you GPT-3 or GPT-4?']
I'm powered by GPT-three.

**Comment by jsedoc** [comment]
This is GPT-4's fault

<img width="1011" alt="image" src="https://github.com/zhudotexe/kani/assets/5974598/fe389354-5119-4f9b-aa5d-03b0c5278a62">

**Comment by zhudotexe** [comment]
Yup! GPT-4 does not know it's not GPT-3. You can verify that the `model` param is passed to the OpenAI API here: https://github.com/zhudotexe/kani/blob/main/kani/engines/openai/engine.py#L117
